### ISSUE TITLE
Don't report Rack metrics?

### ISSUE THREAD

**Issue by infertux** [librato/librato-rails#103]
Is there a way NOT to push `rack.*` metrics? Something like an optional `require 'librato/rack'`?

**Comment by nextmat** [comment]
We started work towards [configurable metric suites](https://github.com/librato/librato-rack/pull/39) to allow this sort of thing a while ago but it needs a bit more love to make it into the final release. 

Currently there isn't a way to turn off only rack metrics while keeping the rails ones. We're always interested in feedback to prioritize future work, so let us know if this is very important for you.

**Comment by infertux** [comment]
Thank you, that sounds good. I would rank this feature as "nice to have" but not very important to me.

**Comment by nextmat** [comment]
@infertux - great, thanks for the clarification!

**Comment by ronwsmith** [comment]
We would like to keep Rack metrics but exclude certain URLs from being reported.  Can that be added onto this issue or would you like a new one created?

For example, we have a health check URL that gets hit 3x per second (1x per second across 3 nodes) by HAProxy and it's driving up costs significantly.

**Comment by nextmat** [comment]
@ronwsmith Do you have multiple URIs you'd like to exclude. A single high activity route shouldn't affect your bill much since with [Service-Side Aggregation](https://www.librato.com/docs/kb/data_processing/ssa.html) all of the requests to every process on all of your machines are reduced to a single (complex) measurement every 60 seconds.

@jderrett - can you comment on the best way to identify which metrics are affecting cost? I know we released some new stuff in that area recently.

**Comment by ronwsmith** [comment]
@nextmat - just one URL.  That aggregation looks like a good way to handle my use case but how do I do it for Rack metrics of that specific URL, ie. `rack.request.method.get`?  I do not want to aggregate metrics on other URLs.

**Comment by jderrett** [comment]
@ronwsmith you can check out your cost per metric on this page:
https://metrics.librato.com/account/top_metrics_report
As @nextmat mentioned, it doesn't seem that a health check URL would generate a bunch of individual sources and drive up costs. If you see something on the list that sticks out, our Support team would be happy to take a look.

Thanks!

**Comment by nextmat** [comment]
@ronwsmith - for clarification, all metrics from librato-rails are already aggregated using Service-Side Aggregation. Otherwise you would see per-process metrics.

**Comment by ronwsmith** [comment]
Thanks @jd and @nextmat!  That top metrics URL pointed me in a totally different direction.  No need to filter URLs and the spikes I saw didn't affect cost.

The most expensive metrics I have are:
```
	frontend.production.rails.view.render_partial
	frontend.production.rails.view.render_partial.time
	frontend.production.rails.view.render_template.time
	frontend.production.rails.view.render_template
```
which have sources reporting at all resolutions 60s and above.  Is that something we can filter out?

**Comment by nextmat** [comment]
@ronwsmith - Unfortunately at the moment there isn't an easy way to turn only those off. As mentioned higher up we started work on configurable suites in https://github.com/librato/librato-rack/pull/39, but mostly this hasn't been a big issue for folks.

If you want a high level of control over exactly what you are spending you can set up librato-rack as middleware manually and turn on the `disable_rack_metrics` [config option](https://github.com/librato/librato-rack/blob/master/lib/librato/rack/configuration.rb#L17). This will disable all the automatic metrics & you will only send your custom ones.

**Comment by nextmat** [comment]
@ronwsmith - just added a branch you might find useful (https://github.com/librato/librato-rails/pull/112). If you are up for running off a branch this should solve your problem until we get the suite management done.

**Comment by bdehamer** [comment]
Implemented configurable metric suites in https://github.com/librato/librato-rails/pull/113 and deployed in version 1.3.0 of `librato-rails`
