### ISSUE TITLE
Cannot use the Heroku log drain prefix as a Heroku user

### ISSUE THREAD

**Issue by jeffblake** [librato/librato-rails#110]
Small issue I noticed,

When you provision Librato through Heroku, a log drain is automatically added, and cannot be removed. If I later go into Librato Integrations, and add a source prefix, while I can then add that drain to Heroku, I'm unable to remove the un-prefixed one. 

I'm planning on signing up directly through Librato anyway - if I can figure out the pricing - but thought I'd pass this along.

**Comment by nextmat** [comment]
@jeffblake - Thanks for the heads up. Yep I think the primary drain is bound to the addon itself.

@jderrett - Can you point Jeff in the right direction for migration in this case?

**Comment by jeffblake** [comment]
It's all good. I went ahead and created a Librato account directly. Nice not having that Heroku bar at the top =)

**Comment by jderrett** [comment]
@jeffblake glad to hear you created a standalone account - please feel free to reach out to us in-app if you have any questions about pricing / usage.  Thanks!
