### ISSUE TITLE
Setting LIBRATO_AUTORUN=1 stops reporting to Librato.

### ISSUE THREAD

**Issue by davidmilo** [librato/librato-rails#111]
We are planning to add some sidekiq tracking to the system so I set `LIBRATO_AUTORUN=1` as it is suggested in the documentation to enable non-web dynos to report as well. However all our reporting stops. I get following error when visiting some of the spaces:
![image](https://cloud.githubusercontent.com/assets/5525649/13738518/d672e3c8-e9c5-11e5-8f6b-6c924bdf8b80.png)

**Comment by nextmat** [comment]
@davidmilo - are you running your processes on heroku?

Are you setting `LIBRATO_AUTORUN` for your web processes as well? If so [this might help](https://github.com/librato/librato-rails/wiki/Monitoring-Background-Workers#monitoring-long-running-threaded-workers-sidekiq-etc). This might be the issue?

> Note that you should not set LIBRATO_AUTORUN=1 for your web processes as it will likely interfere with reporting from them. The best ways to isolate this setting for LIBRATO_AUTORUN are to include this part of the config in a wrapper script for starting your workers or put it on the workers' line in your Procfile if you are using one.

**Comment by nextmat** [comment]
@davidmilo - Let us know if you are still having issues with this or ping support at support@librato.com.

**Comment by davidmilo** [comment]
Thanks, that was indeed the issue.

**Comment by nextmat** [comment]
Awesome, glad that fixed it for you.
