### ISSUE TITLE
Is this gem thread-safe?

### ISSUE THREAD

**Issue by samandmoore** [librato/librato-rails#115]
Hi,

I was interested in using this gem in my multi-threaded rails application until I ran across this documentation for the underlying librato-metrics ruby client: https://github.com/librato/librato-metrics#thread-safety

Can you provide some clarity on the thread-safety guarantees of this gem?

Thanks!

**Comment by nextmat** [comment]
Yep, this gem and [librato-rack](https://github.com/librato/librato-rack) are fully threadsafe. Happy to answer any more specific questions if you have them.

**Comment by samandmoore** [comment]
Thank you. :

**Comment by nextmat** [comment]
No prob, happy to help. :-)
