### ISSUE TITLE
Ever increasing memory usage

### ISSUE THREAD

**Issue by chrisrecalis** [librato/librato-rails#116]
Hi,

I'm seeing non-stop memory growth when I add the librato-rails gem to my project. I am currently running `rails 4.2.5` `ruby-2.3.0` `librato-rails 1.3.0`. Currently deployed on heroku and I'm hitting the memory quota daily. If I use just `librato-metrics 1.6.1` and do all the tracking myself I do not see this. I ran derailed_benchmarks mem_over_time on a blank rails app and this is what I'm seeing. (this is over a span of 10 minutes both with a flush interval of 5 seconds)

![image 3](https://cloud.githubusercontent.com/assets/5234070/14994141/402dcaa6-113c-11e6-90a0-e8027c12c966.png)

**Comment by nextmat** [comment]
@chrisrecalis - Thanks very much for the report and also for benching on a clean app. We take memory leaks very seriously. As an interim measure you may want to try downgrading to v0.11.1 while we sort this out.

@bdehamer - can you dig into this & repro? If you can't look into this soon, LMK and I'll see about taking a look.

**Comment by chrisrecalis** [comment]
@nextmat Sorry I may have actually jumped the gun on this and didn't allow the test to go on long enough. Although the bloat is very high which limits the number of workers I'm able to run. After running about 1,000,000 requests I see the objects being garbage collected. Sorry for the inconvenience

![image 4](https://cloud.githubusercontent.com/assets/5234070/14995047/dc9a618e-1140-11e6-8d29-9b3fc1381979.png)

**Comment by nextmat** [comment]
@chrisrecalis - Thanks for the update. We should still look into this to reduce object churn if we can.

**Comment by bdehamer** [comment]
@chrisrecalis I spent some time yesterday trying to reproduce the results you were seeing
<img width="477" alt="screen shot 2016-05-03 at 2 51 58 pm" src="https://cloud.githubusercontent.com/assets/398027/15018802/171bb238-11d0-11e6-83bf-fc79cc14bcfd.png">

As you can see, I wasn't able to replicate the big growth in memory that you were seeing (this was a 20 min run of the derailed_benchmarks `mem_over_time` test). 

Do you have any code that you can share with us that would help us to better replicate the issue? Maybe whatever code is being executed in the controller action that is being exercised by the benchmark.

Thanks.

**Comment by chrisrecalis** [comment]
Memory gets sporadic when the flush interval is lowered. I know from the docs not to touch this for production environments. I'm just a little confused because on the website for metrics under set default attributes you can select how often the metric is supposed to report. For example say through the website I set the metric's `Metric reports every` to 30 seconds. I set the flush interval to 60 seconds (default) do I now lose accuracy since it waits 60 seconds to aggregate the results then send it? I do have metrics I would like to send more frequently but I've since moved them to their own aggregator using the `librato-metrics` gem

![image 5](https://cloud.githubusercontent.com/assets/5234070/15022450/b9c52982-11f9-11e6-8a07-673e8596113d.png)

**Comment by nextmat** [comment]
The flush interval option is really only there to make debugging easier for initial setup. You may get incorrect data if you use it in production since the metrics are all set up for a 60s period.

Can you give me an example of a use case where you want something higher resolution? 

The only potential issue with using librato-metrics directly is you will have to handle thread backgrounding for reporting yourself, otherwise the submission can happen during the service of a request and delay it. librato-rails does all of this for you.

I'm not surprised that you see higher object allocation at higher flush rates as the internal histograms and tracking memory structures get reset between submissions.

**Comment by chrisrecalis** [comment]
How would you go about displaying requests/second instead of requests/minute on the dashboard? Would this be a composite metric? I also have custom events I would like to see at a higher resolution these are short burst events that happen within a minute (this is why I moved them to `librato-metrics` as it doesn't pertain to `librato-rails`). I know the default metric is reported at 60s but its easily changeable on the dashboard. I'm just starting out with Librato so I'm probably going down the wrong path here.

**Comment by nextmat** [comment]
@chrisrecalis - There are actually multiple ways to achieve what you're after. To get you the best help can you shoot an email to `support@` or open a ticket from inside the app?
