### ISSUE TITLE
Support the ability to filter metrics by instrument_action

### ISSUE THREAD

**Issue by gmckeever** [librato/librato-rails#121]
For metrics automatically reported, offer the ability to ignore metrics by a certain action. Currently you can [create additional metrics by action](https://github.com/librato/librato-rails#instrument_action), but not ignore them if they are already reported by default.

ex. `exclude_action :create'

**Comment by nextmat** [comment]
What is the use case here? Are we trying to remove a specific action from the aggregate metrics or doing something like `instrument_action :all` and then exclude a few?

**Comment by gmckeever** [comment]
@nextmat pointed out offline that there is already an issue for this #48 which covers the same use case (filtering an action from the aggregate metrics). I'll close this issue out.
