### ISSUE TITLE
Librato.increment doesn't respect metric prefix

### ISSUE THREAD

**Issue by recursify** [librato/librato-rails#124]
From my rails app, I call `Librato.increment "foo.bar"` and I've defined a prefix of `staging` in my librato.yml file.

expected: I see a metric called "staging.foo.bar" in Librato
actual: the metric is called "foo.bar"

The auto generated metrics `rails.*` and `rack.*` all respect the prefix.

**Comment by recursify** [comment]
Solved this one myself.  If you separately configure librato-rack, you end up with two instances (which may be configured with a different `prefix`).  This can result in either doubly reported metrics, or metrics with an unexpected prefix.

Solution is to remove the `use Librato::Rack` from your config.

**Comment by nextmat** [comment]
Glad to hear you sorted this out - let us know if there is anything else we can help with!
