### ISSUE TITLE
fix Ruby 2.4 deprecations

### ISSUE THREAD

**Issue by attack** [librato/librato-rails#127]
[librato-rack](https://github.com/librato/librato-rack) was [updated](https://github.com/librato/librato-rack/commit/ed26ebae20ac30049cbdad52268b2c66e1eceaa7) to 1.1.0 to fix deprecations for Ruby 2.4.

How do you feel about updating to allow librato-rack 1.1.0 in the [gemspec](https://github.com/librato/librato-rails/blob/master/librato-rails.gemspec#L28) ?

**Comment by nextmat** [comment]
Thanks for asking, yes we still have a little work to do for 2.4 support here and bumping the librato-rack version will be part of that. Opened #128 to be a bit more transparent about what is needed.

**Comment by nextmat** [comment]
Released in v1.4.2
