### ISSUE TITLE
Librato.timing should mention that values are in milliseconds

### ISSUE THREAD

**Issue by jderrett** [librato/librato-rails#133]
If you do

```
Librato.timing 'my.timer' do
  Librato.measure 'some.operation', sleep(1)
end
```
you'll see that `some.operation` gets a value of `1` but `my.timer` gets a value of `1,001` (ish). This behavior doesn't appear to be mentioned in the docs for `Librato.timer`

**Comment by nextmat** [comment]
To clarify you mean there should be better documentation that values are ms not sec?

**Comment by jderrett** [comment]
Yep, just around https://github.com/librato/librato-rails#timing we should probably mention that timings are in ms.
