### ISSUE TITLE
Will you accept and release patches? (Is this gem still maintained? )

### ISSUE THREAD

**Issue by anaulin** [librato/librato-rails#146]
I'm considering adding this to one of my Rails projects, but I notice the gem seems unmaintained.

I might be able to contribute a couple of PRs to make sure that at least Rails 5.1 is supported by this gem. Do any of the maintainers have the bandwidth to review, approve and release changes?

If not, do you have a recommendation for an alternate way to send custom metrics to Librato from a Rails application?

Thanks in advance! 🙇🏼‍♀️

**Comment by mbeale** [comment]
The best path forward would be to queue sidekiq (or similar) background jobs to send metrics.   You could also use statsd if you need to use an aggregator before sending the metrics to librato.  The library isn't currently being updated.

**Comment by anaulin** [comment]
Got it. Thanks for the quick response, @mbeale.
