### ISSUE TITLE
Support suites to allow users to turn sets of metrics on and off

### ISSUE THREAD

**Issue by nextmat** [librato/librato-rails#71]
Ideally we should support sets of suites that the gem can be configured to turn on or off so if there is a set of metrics you don't really care about and you are running at volume you can turn them off.

A rough stab at what I'm thinking:

**rack**

    rack.request.total
    rack.request.time
    rack.request.exceptions
    rack.request.queue.time
    rack.request.slow

**rack_method**

    rack.request.method.get
    rack.request.method.get.time
    rack.request.method.post
    ...

**rack_status**

    rack.request.status.200
    rack.request.status.200.time
    rack.request.status.2xx
    rack.request.status.2xx.time
    ...

**rails**

    rails.request.total
    rails.request.time
    rails.request.time.db
    rails.request.time.view
    rails.request.exceptions
    rails.request.slow

**rails_method**

    rails.request.method.get
    rails.request.method.get.time
    rails.request.method.post
    ...

**rails_status**

    rails.request.status.200
    rails.request.status.200.time
    rails.request.status.2xx
    rails.request.status.2xx.time
    ...

**rails_mail**

    rails.mail.sent
    rails.mail.received

**rails_sql**

    rails.sql.queries
    rails.sql.selects
    rails.sql.inserts
    rails.sql.updates
    rails.sql.deletes

etc.

`rack.processes` will be exclusive of a suite and will always be reported as a way to monitor total processes reporting

I'm thinking with env config something along the lines of:

    LIBRATO_SUITES=rack,rails,rails_sql

..if you want to select your own list or alternately:

    LIBRATO_SUITES_EXCEPT=rack_method,rails_mail

If you want everything but a few. I'm thinking to implement this fairly soon, thoughts/improvements are welcome.

**Comment by jeffblake** [comment]
Bumping this. 

`rails.view.render_partial`
`rails.view.render_partial.time`

are both heavy hitters for me that I need disabled.

**Comment by bdehamer** [comment]
Implemented in https://github.com/librato/librato-rails/pull/113 and released in version 1.3.0 of `librato-rails`
