### ISSUE TITLE
Add source details to mail deliveries

### ISSUE THREAD

**Issue by sgringwe** [librato/librato-rails#91]
Right now librato-rails adds mailer gauges by default which is great. It would be 10x better IMO if it were to include source details (what type of email is being sent). could this be added?

**Comment by sgringwe** [comment]
It looks like unfortunately the only relevant info received from the subscription is the mailer and subject. Feel free to disregard this.

**Comment by nextmat** [comment]
@sgringwe You could definitely add support for including this as a custom instrumentation yourself, but yeah this info isn't included via the built-in ActiveSupport::Notifications instrumentation.
